### ISSUE TITLE
Inferring issues

### ISSUE THREAD

**Issue by St1ngray** [KwatME/model_and_infer#14]
![screenshot from 2019-02-20 15-21-57](https://user-images.githubusercontent.com/5835456/53132668-42114180-3525-11e9-8c8a-8e8bd9f586cc.png)

![screenshot from 2019-02-20 15-11-42](https://user-images.githubusercontent.com/5835456/53132679-46d5f580-3525-11e9-84ed-104801a82408.png)

![screenshot from 2019-02-20 15-22-27](https://user-images.githubusercontent.com/5835456/53132683-4a697c80-3525-11e9-8b90-2357be74a220.png)

**Comment by KwatME** [comment]
I fixed these issues. You can get the updated notebook 14 now.
