### ISSUE TITLE
NB5: Matching code

### ISSUE THREAD

**Issue by KateKraft** [KwatME/model_and_infer#6]
You match W.T (which is Pattern X Gene) to signal.T (Sample X Gene) and feature_x_sample (Gene X Sample). But You cant match W.T to feature_x_sample because the columns have different kinds of values, so when the cell runs, you see H patterns being compared to feature_x_sample genes, but you don't see W patterns being compared to feature_x_sample samples. 

You need to transpose feature_x_sample for the W iteration to be consistent, or just dont match H or W to feature_x_sample.

![screen shot 2018-12-11 at 11 43 38](https://user-images.githubusercontent.com/20215501/49825761-0f371a00-fd3a-11e8-86a1-1c3b234f9587.png)

**Comment by KwatME** [comment]
Fixed.
