### ISSUE TITLE
NB5: Do we need these plots?

### ISSUE THREAD

**Issue by KateKraft** [KwatME/model_and_infer#8]
It seems like the value in these plots is to be able to hover over and see which celllines/samples are most enriched in whatever component, was this what you were going for or is there another purpose?

What can this plot do for us that the h/w matrix cant?

![screen shot 2018-12-11 at 12 02 27](https://user-images.githubusercontent.com/20215501/49826813-b0bf6b00-fd3c-11e8-9eb0-0b2d59957852.png)

**Comment by KateKraft** [comment]
Less is always better, so if theres not a clear value maybe we should remove them.

**Comment by KwatME** [comment]
Yes. These plots show how we make signature.

**Comment by KateKraft** [comment]
Still don't understand, but we can talk about it later.
