### ISSUE TITLE
NB5: Bubble map code

### ISSUE THREAD

**Issue by KateKraft** [KwatME/model_and_infer#9]
Before my bubble maps were empty because my FEATURES_TO_PEEK genes didnt include the context signs (-) or (+) So I added this code to search for my features to peek in the signal matrix index:
```
features_to_peek_with_context_sign = []

for feature in FEATURES_TO_PEEK:

    for index, series in signal.iterrows():
        
        if feature in index:
            
            features_to_peek_with_context_sign.append(index)
```
![screen shot 2018-12-11 at 13 07 57](https://user-images.githubusercontent.com/20215501/49830556-5deab100-fd46-11e8-8c61-71b7effc9d6a.png)

**Comment by KwatME** [comment]
Fixed.
